"""Measure five simple collision boxes per prepared Hedra width.

Two base boxes, two support boxes and one seat retain the open space beneath
the bench. Triangle clipping includes edges crossing a height boundary.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from generate_exedra_shape import clip

ROOT = Path(__file__).resolve().parents[1]
MESH = ROOT / 'src/main/resources/assets/daedalon/models/mesh'
TARGET = ROOT / 'src/main/java/com/oliver/daedalon/block/HedraShape.java'


def boxes(width):
    vertices, triangles = [], []
    for line in (MESH / f'hedra_{width}m.obj').read_text().splitlines():
        if line.startswith('v '):
            vertices.append(tuple(map(float, line.split()[1:])))
        elif line.startswith('f '):
            triangles.append([vertices[int(v.split('/')[0]) - 1] for v in line.split()[1:]])
    result = []
    for y0, y1 in ((0.0, 0.075), (0.075, 0.35), (0.35, 0.5)):
        spans = ((-width/2, width/2),) if y0 == 0.35 else ((-width/2, 0), (0, width/2))
        for x0, x1 in spans:
            points = []
            for triangle in triangles:
                if (max(v[0] for v in triangle) < x0 or min(v[0] for v in triangle) > x1
                        or max(v[1] for v in triangle) < y0 or min(v[1] for v in triangle) > y1):
                    continue
                clipped = triangle
                for axis, boundary, greater in ((0,x0,True), (0,x1,False), (1,y0,True), (1,y1,False)):
                    clipped = clip(clipped, axis, boundary, greater)
                points.extend(clipped)
            if points:
                result.append(tuple(min(v[i] for v in points) for i in range(3))
                              + tuple(max(v[i] for v in points) for i in range(3)))
    return result


def content():
    groups = []
    for width in (2, 3, 4):
        rows = ['            {' + ', '.join(f'{v:.9f}' for v in box) + '},' for box in boxes(width)]
        groups.append('        { // ' + str(width) + 'm\n' + '\n'.join(rows) + '\n        },')
    return ('package com.oliver.daedalon.block;\n\n'
            '// Generated by tools/generate_hedra_shape.py; centred world-metre coordinates.\n'
            'final class HedraShape {\n'
            '    private HedraShape() {}\n'
            '    static final double[][][] BOXES = {\n' + '\n'.join(groups) + '\n    };\n}\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = content()
    if args.check:
        if TARGET.read_text() != expected:
            raise SystemExit('HedraShape.java needs regeneration')
        print('Hedra collision profile matches all three meshes')
    else:
        TARGET.write_text(expected, encoding='utf-8', newline='\n')
