"""Generate a bounded curved collision profile from the approved 3m OBJ.

Twelve width strips and three height bands retain the open front and the
lower seat without a solid bounding box. Minecraft shares all 12 cached shapes
across materials. Clipping includes triangle edges, not just source vertices.
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src/main/resources/assets/daedalon/models/mesh/exedra_3m.obj'
TARGET = ROOT / 'src/main/java/com/oliver/daedalon/block/ExedraShape.java'


def clip(points, axis, boundary, greater):
    result = []
    for start, end in zip(points, points[1:] + points[:1]):
        a = start[axis] >= boundary if greater else start[axis] <= boundary
        b = end[axis] >= boundary if greater else end[axis] <= boundary
        if a:
            result.append(start)
        if a != b:
            t = (boundary - start[axis]) / (end[axis] - start[axis])
            result.append(tuple(start[i] + t * (end[i] - start[i]) for i in range(3)))
    return result


def boxes():
    vertices, triangles = [], []
    for line in SOURCE.read_text(encoding='utf-8').splitlines():
        if line.startswith('v '):
            vertices.append(tuple(map(float, line.split()[1:])))
        elif line.startswith('f '):
            triangles.append([vertices[int(v.split('/')[0]) - 1] for v in line.split()[1:]])
    result = []
    for y0, y1 in ((0.0, 0.4), (0.4, 0.55), (0.55, 1.0)):
        for column in range(12):
            x0, x1 = -1.5 + column / 4, -1.5 + (column + 1) / 4
            points = []
            for triangle in triangles:
                if (max(v[0] for v in triangle) < x0 or min(v[0] for v in triangle) > x1
                        or max(v[1] for v in triangle) < y0 or min(v[1] for v in triangle) > y1):
                    continue
                clipped = triangle
                for axis, boundary, greater in ((0,x0,True), (0,x1,False), (1,y0,True), (1,y1,False)):
                    clipped = clip(clipped, axis, boundary, greater)
                points.extend(clipped)
            if points:
                result.append((x0 / 3, min(v[1] for v in points), min(v[2] for v in points),
                               x1 / 3, max(v[1] for v in points), max(v[2] for v in points)))
    return result


def content():
    rows = ['        {' + ', '.join(f'{v:.9f}' for v in box) + '},' for box in boxes()]
    return ('package com.oliver.daedalon.block;\n\n'
            '// Generated by tools/generate_exedra_shape.py; X is a fraction of selected width.\n'
            'final class ExedraShape {\n'
            '    private ExedraShape() {}\n'
            '    static final double[][] BOXES = {\n' + '\n'.join(rows) + '\n    };\n}\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = content()
    if args.check:
        if TARGET.read_text(encoding='utf-8') != expected:
            raise SystemExit('ExedraShape.java needs regeneration')
        print('Exedra collision profile matches the approved mesh')
    else:
        TARGET.write_text(expected, encoding='utf-8', newline='\n')
