"""Measure the hollow Monopteros shell in 32 horizontal bands.

Triangle clipping includes faces spanning a band. Radii enclose the supplied
mesh; the cached game profile rounds the shell outwards to quarter-block cells.
"""
from pathlib import Path
import math, argparse
from generate_exedra_shape import clip

ROOT = Path(__file__).resolve().parents[1]
MESH = ROOT/'src/main/resources/assets/daedalon/models/mesh/monopteros_8m.obj'
TARGET = ROOT/'src/main/java/com/oliver/daedalon/block/MonopterosProfile.java'

def profile():
    vertices, triangles = [], []
    for line in MESH.read_text().splitlines():
        if line.startswith('v '): vertices.append(tuple(float(v)/8 for v in line.split()[1:]))
        elif line.startswith('f '): triangles.append([vertices[int(v.split('/')[0])-1] for v in line.split()[1:]])
    height = max(v[1] for v in vertices)
    rings=[]
    for band in range(32):
        y0, y1 = height*band/32, height*(band+1)/32
        radial=[]
        for tri in triangles:
            if max(v[1] for v in tri)<y0 or min(v[1] for v in tri)>y1: continue
            polygon=clip(clip(tri,1,y0,True),1,y1,False)
            for i,a in enumerate(polygon):
                b=polygon[(i+1)%len(polygon)]
                dx,dz=b[0]-a[0],b[2]-a[2]
                t=max(0,min(1,-(a[0]*dx+a[2]*dz)/(dx*dx+dz*dz))) if dx*dx+dz*dz else 0
                radial.extend((math.hypot(a[0],a[2]),math.hypot(a[0]+t*dx,a[2]+t*dz)))
        rings.append((min(radial),max(radial)))
    return height,rings

def content():
    height,rings=profile()
    return ('package com.oliver.daedalon.block;\n\n'
            '// Generated by tools/generate_monopteros_shape.py; metres per metre of diameter.\n'
            'final class MonopterosProfile {\n    private MonopterosProfile() {}\n'
            f'    static final double HEIGHT = {height:.9f};\n'
            '    static final double[][] RADII = {\n'
            + ''.join(f'        {{{inner:.9f}, {outer:.9f}}},\n' for inner,outer in rings)
            + '    };\n}\n')

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    expected=content()
    if args.check:
        if TARGET.read_text()!=expected: raise SystemExit('MonopterosProfile.java needs regeneration')
        print('Monopteros shell matches the source mesh')
    else: TARGET.write_text(expected,encoding='utf-8',newline='\n')
